title: Anatomy Package
description: Data sets code and use cases for the Anatomy Package
baseurl: ""
url: "https://braincircuits.info"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lunr-js-search

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - LICENSE
  - README.md
